apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  namespace: solar-system
  labels:
    app: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: webdevloper/solar-system:88fd9df114e1ad2289640a1e4deb4568c61260f4
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: mongo-db-creds
---
apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  namespace: solar-system
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
